### ISSUE TITLE
v3.0 Tracking Issue

### ISSUE THREAD

**Issue by MikePall** [LuaJIT/LuaJIT#1092]
This is a locked tracking issue. Discussion takes place in individual issues. Related issues will be created by the admins, when needed.

Do not open issues or PRs for any of these, or for unsolicited features. Do not work on or submit code, unless a discussion has been fully resolved _and_ you have been tasked with the implementation.

Issues listed here **may** be handled in the v3.0 development cycle, but there's no guarantee for that.

The following issues are grouped by their scope. The groups are listed in approximate dependency/implementation order.

## Initial Bringup and Cleanup
* TBD: Scope and non-scope of v3.0 branch.
* TBD: Open design issues, implementation order, schedule.
* TBD: Sponsoring for continued maintenance and development.
- [ ] Open v3.0 branch
- [ ] Remove obsolete archs and arch-variants, see status page
- [ ] Remove obsolete target platforms
- [ ] TBD

## Compile all/most standard library functions
* REQ: Simplify/unify this between interpreter and JIT backend.
* REQ: Do not compromise pure interpreter performance (Consoles, iOS).
* TBD: Make FFI mandatory? Needs pre-compiled equivalent for interpreter.
* TBD: More discussion and planning required.
- [ ] #10
- [ ] #15
- [ ] #22
- [ ] [ISSUE] Compile `os.*` and `io.*` functions

## Compile all/most bytecodes
- [ ] [ISSUE] Compile closure creation, TBD effects on IR consistency

## Syntax Extensions
* REQ: Must not affect existing source code. Bytecode changes are OK.
- [ ] #63, TBD metamethods or not
- [ ] [ISSUE] Ternary `a?b:c` operator
- [ ] [ISSUE] Floor division operator, TBD: `//` already used by third parties
- [ ] [ISSUE] Soft `continue` keyword
- [ ] [ISSUE] Allow underscores in number literals

## Garbage Collector
* TBD: Initial scope and MVP.
- [ ] #38
- [ ] [ISSUE] Public API to set allocator limits
- [ ] [ISSUE] Allocator hardening
- [ ] [ISSUE] Account for auxiliary memory in GC pacing, TBD `ffi.gc` size parameter
- [ ] [ISSUE] Memory profiler

## Ports
* [List of current and planned ports](https://luajit.org/status.html#architectures).
- [ ] [ISSUE] Enable unaligned access for more targets
- [ ] #628, TBD RISC-V RV64 RVA22+, TBD unmergable

## Cleanups, Semantic Consistency
- [ ] [ISSUE] Cleanup/simplify `IR_HREF`, TBD call helpers for uncommon paths
- [ ] [ISSUE] Consistent behavior of FP to unsigned int conversions (#415) (https://github.com/LuaJIT/LuaJIT/issues/865#issuecomment-1192440955)
- [ ] [ISSUE] 32/64 bit constants and widening (#1086)
- [ ] [ISSUE] Eliminate `cur_L` (#1066)

## FFI Feature Completion
- [ ] #28
- [ ] #29
- [ ] #57
- [ ] #27

## Bytecode Portability and Determinism
* TBD: Maybe convert all ports (even 32 bit) to `LJ_FR2`? `LJ_GC64` has a performance impact, but `LJ_FR2` very little.
- [ ] #993
- [ ] #1008

## JIT-Compiler Enhancements
- [ ]  [ISSUE] Allocation sinking enhancements (#651) (#652)

## Pattern Matching Rewrite
* REQ: Only handles Lua patterns, not full regex. No extensions planned.
* REQ: Must be fast when only interpreted.
* REQ: Must be fast for one-off use, too. Avoid allocating memory.
* REQ: Handle dynamic patterns (misuse) reasonably.
* FYI: 2-phase parse/exec bytecode-based prototype available, but does not fulfill all REQ.
* TBD: Explore lazy parse + cache + trace approach. Explore QDFA.
* TBD: Prevent ReDOS or not, consider implementation complexity and efficiency.
- [ ] [ISSUE] Pattern matcher rewrite
- [ ] [ISSUE] Pattern matching methods for string buffers
- [ ] [ISSUE] JIT-compiled pattern matching

## Repurpose Global+ Scope
* GOAL: Improve performance for resolving module methods.
* GOAL: Remove need for `local abs = math.abs` red tape.
* REQ: Make this mode optional behind a CLI flag (name TBD).
* TBD: Resolve early during bytecode generation to an upvalue-like. Bind at load.
* TBD: Required consistency level, expensive to prevent writes to module table.
- [ ] [ISSUE] Repurpose global+ scope

## Debugging
* TBD: Check third-party extensions that dig into VM internals.
* TBD: Evaluate demand.
- [ ] [ISSUE] Dump on assertion, TBD dump format, dump analysis, hookable
- [ ] [ISSUE] Public API for VM introspection
- [ ] [ISSUE] Fast breakpoints, TBD bytecode/mcode patching

## Unconfirmed, Unclear
* TBD: More likely to be moved to following versions.
* TBD: any enhancement issues not yet tagged with a version
- [ ] Make FFI mandatory
- [ ] Make compiler extensible by loadable modules
- [ ] Split optional features to loadable modules, default is builtin
